.PHONY: all bsv sv doc html python ral

# Default: generate BSV from RDL, compile with bsc, output Verilog to ../verilog/
all: bsv

bsv: {{ip_name}}.rdl
	peakrdl bsv {{ip_name}}.rdl -o ../bsv

# Generate SystemVerilog register block directly from RDL (no BSC step)
sv: {{ip_name}}.rdl
	peakrdl regblock --cpuif axi4-lite-flat --default-reset arst_n {{ip_name}}.rdl -o ../verilog

doc: {{ip_name}}.rdl
	peakrdl markdown {{ip_name}}.rdl  -o ../doc/registers.md
	sed -ie 's/## {{ip_name|capitalize}}_Reg address map/# {{ip_name|capitalize}}_Reg address map/'  ../doc/registers.md

html:
	mkdir -p html
	peakrdl html {{ip_name}}.rdl  -o html

python:
	peakrdl python {{ip_name}}.rdl -o ../tb/ --async

# Generate cocotb RAL model from RDL for use by tb/test_default.py
ral: {{ip_name}}.rdl
	peakrdl cocotb_ralgen {{ip_name}}.rdl -o ../tb/
