title={{ip_name}} IP
client=TBD Client Name
docstatus=Working Document
document-sha=$(shell git rev-parse --short HEAD )
authoremail={{email}}
files=refman.md {{ip_name}}.md registers.md ai.md
variables=-V title:"$(title)" -V client:"$(client)" -Vauthoremail:$(authoremail) -V document-sha:$(document-sha) -V status:"$(docstatus)"
doc:
	pandoc --lua-filter=$(HOME)/.pandoc/diagram.lua $(variables) -o reference_manual.pdf -s --template=$(HOME)/.pandoc/template/dyu/refman.template $(files)
