tst=default
TOPLEVEL=mk{{ip_name|capitalize}}.v
MODULE=test_$(tst)
SIM_BUILD = ${tst}_build
ifeq ($(tst), default)
	VERILOG_DIR=$({{ip_name|capitalize}}_ROOT)/verilog
	VERILOG_SOURCES +=$(VERILOG_DIR)/$(TOPLEVEL)
else
	VERILOG_DIR=$({{ip_name}}_ROOT)/someother_verilog
	VERILOG_SOURCES +=$(VERILOG_DIR)/design/$(TOPLEVEL)
endif

SIM ?= icarus
TOPLEVEL_LANG ?= verilog
include $(shell cocotb-config --makefiles)/Makefile.sim
stem: 
	echo $(tst)
	verilator -Wno-fatal -y $(BSV_LIBRARY) -I../bsv -xml-only --bbox-sys $(VERILOG_SOURCES)
	java -jar /tools/saxon/saxon-he-10.5.jar -xsl:stems.xsl obj_dir/Vcl_id_defines.xml>top.stem
